### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Olga-Skoroded** [Evgeny3101/task2#37]
По БЭМ нельзя задавать внешнюю геометрию блокам 
![Снимок экрана от 2021-07-27 16-54-57](https://user-images.githubusercontent.com/68814270/127135520-1aa6a4c2-e6f1-4f13-ba4b-20a62c166401.png)
![Снимок экрана от 2021-07-27 16-59-34](https://user-images.githubusercontent.com/68814270/127135541-01df8bac-bef1-4b91-a020-da48a95586d5.png)

**Comment by Olga-Skoroded** [comment]
По нашим стандартам миксы запрещены
![Снимок экрана от 2021-08-17 18-48-45](https://user-images.githubusercontent.com/68814270/129738883-246a5912-9b40-46f1-b837-9c1d63c3e8da.png)

**Comment by Olga-Skoroded** [comment]
В стилях для блока ui-kit содержатся стили для других блоков, такого не должно быть
![Снимок экрана от 2021-08-17 18-49-25](https://user-images.githubusercontent.com/68814270/129738921-1977548f-b6cb-41a8-8551-08101decba24.png)

**Comment by Olga-Skoroded** [comment]
Вот тут внутри одного миксина два блока, у блока title некорректный модификатор, должен быть модификатор типа ключ-значение, например, _size_large 
![Снимок экрана от 2021-11-29 11-02-15](https://user-images.githubusercontent.com/68814270/143806921-c29322f4-2acb-4793-ba4c-deae05818ddf.png)

**Comment by Olga-Skoroded** [comment]
Опять в стилях одного блока лежат стили другого блока
![Снимок экрана от 2021-11-29 11-06-14](https://user-images.githubusercontent.com/68814270/143807246-961fb481-0d5f-406e-b318-4e68d635ad0b.png)

**Comment by Olga-Skoroded** [comment]
Вот тут тоже нужно порядок навести, не устанавливать маржины для блока, привести в соотвествие именование директории, файла, блока. В стилях в куче лежат и глобальные стили, и стили для разных блоков
![Снимок экрана от 2021-11-29 11-13-53](https://user-images.githubusercontent.com/68814270/143807985-49de9665-4d44-4b89-8293-3a173af270df.png)
![Снимок экрана от 2021-11-29 11-14-04](https://user-images.githubusercontent.com/68814270/143807995-6b81afcd-578b-4661-87f9-007fe842a9f7.png)
![Снимок экрана от 2021-11-29 11-14-48](https://user-images.githubusercontent.com/68814270/143808018-3f0a1c32-7b5b-4220-ac6b-79f07fc27e00.png)
)

**Comment by Evgeny3101** [comment]
> Вот тут внутри одного миксина два блока, у блока title некорректный модификатор, должен быть модификатор типа ключ-значение, например, _size_large ![Снимок экрана от 2021-11-29 11-02-15](https://user-images.githubusercontent.com/68814270/143806921-c29322f4-2acb-4793-ba4c-deae05818ddf.png)

 "внутри одного миксина два блока" оставил только те у которых только класс и имеют разные элементы(H1, H2 и тд)

**Comment by Evgeny3101** [comment]
> Вот тут внутри одного миксина два блока, у блока title некорректный модификатор, должен быть модификатор типа ключ-значение, например, _size_large ![Снимок экрана от 2021-11-29 11-02-15](https://user-images.githubusercontent.com/68814270/143806921-c29322f4-2acb-4793-ba4c-deae05818ddf.png)


 "внутри одного миксина два блока" оставил только те у которых только класс и имеют разные элементы(H1, H2 и тд)
 title, button и text-field. не знаю(и не нашел) как сделать переменную в PUG на элемент без условий(через if например), 
И мне показался лучшим вариантом подключать такие стили в шаблоне чтоб не дублировать подключение везде и просто делать еще один блок там
