### ISSUE TITLE
Подключение библиотек

### ISSUE THREAD

**Issue by Olga-Skoroded** [Evgeny3101/task2#47]
А почему либы просто лежат в проекте, а не установлены через npm? 
![Снимок экрана от 2021-11-29 11-20-06](https://user-images.githubusercontent.com/68814270/143808409-ef8b561c-99ec-450c-8c03-ff7ca06ef55b.png)

**Comment by Evgeny3101** [comment]
по range-slider это мое второе задание, не помню требования делать доступным его через npm...  делать? 
по bemto исправлял ошибку в библиотеке.
 fork не делал так как проект учебный и не уверен что дальше буду им пользоваться

**Comment by Olga-Skoroded** [comment]
Поняла) Думаю, что можно так оставить тогда
